name: CI file

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest]
          python-version: ["3.9", "3.10"]
    name: lint (OS> ${{ matrix.os }}, Python> ${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} 
      - name: Install dependencies
        run: pip install flake8 mypy
      - name: Run linter
        run: |
          flake8 .
          mypy --ignore-missing-imports --explicit-package-bases .
        shell: bash

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest]
          python-version: ["3.9", "3.10"]
    if: github.event_name == 'workflow_dispatch'
    name: test (OS> ${{ matrix.os }}, Python> ${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest tests/functional
